baseurl = "https://zorig.ch/"
languageCode = "en-us"
title = "Zorig Reinigungen"
theme = "creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Zorig Reinigungen"
	description = "Reinigung Putzen Luzern"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Zorig Reinigungen"

		[params.navigation.links]
			about     = "Über uns"
			services  = "Dienstleistungen"
			portfolio = "Portfolio"
			contact   = "Kontakt"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Ihre Zufriedenheit ist unsere Garantie"
		subtitle   = "Zorig Reinigungen bietet zuverlässige, gründliche und preiswerte Reinigungen von Büro und privaten Räumlichkeiten."
		buttonText = "Lernen Sie uns kennen!"


	# About section
	[params.about]
		headline    = "Wir reinigen alles"
		description = "Sind Sie auf der Suche nach einer Haushaltsreinigung auf die Sie sich verlassen können? Sie müssen nicht weiterschauen. Wir sind Zorig Reinigungen und sind da, wann und wo Sie uns brauchen. Seit 2010 haben wir uns dazu verpflichtet, die beste Reinigung für unsere Kunden in Luzern und Umgebung zu garantieren. Wir werden auch Ihre Erwartungen übertreffen."
		buttonText  = "Verlangen Sie ein Angebot"


	# Service section
	[params.services]
		headline = "Zu Ihren Diensten"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Blitzsauber"
            description = "Endreinigung mit Abnahmegarantie!"

   [[params.services.list]]
			icon = "fa-globe"
			title = "Überall"
			description = "Wir sind dort wo Sie uns brauchen!"

		[[params.services.list]]
            icon = "fa-building-o"
            title = "Fürs Geschäft"
            description = "Wir reinigen auch Büros und Geschäftsräume."

        [[params.services.list]]
            icon = "fa-refresh"
            title = "Sauberkeitsabonnement"
            description = "Profitieren Sie jetzt von einem Reinigungsabo!"


    # Portfolio modals
#	[params.portfolio.modal]
#        client = "Client"
#        date = "Date"
#        category = "Category"
#        buttonText = "Close"

    # Aside section
#	[params.aside]
	#	headline = "Get the Creative Theme for Hugo"

#		[params.aside.button]
#			text = "Download now"
#			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Kontaktieren Sie uns noch heute!"
		description = "Sind Sie bereit für ein neues Gefühl von Sauberkeit?"
		phone = "+41 41 240 27 41"
		email = "info@zorig.ch"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""

	[outputs]
home = [ "HTML", "RSS", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
